// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventPayload  []byte                 `protobuf:"bytes,2,opt,name=event_payload,json=eventPayload,proto3" json:"event_payload,omitempty"`
	DeskId        string                 `protobuf:"bytes,3,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // empty if desk has no parent group
	Notes         []*Note                `protobuf:"bytes,6,rep,name=notes,proto3" json:"notes,omitempty"`
	Session       []*Message             `protobuf:"bytes,7,rep,name=session,proto3" json:"session,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,8,rep,name=resources,proto3" json:"resources,omitempty"`
	Options       map[string]string      `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // executor params from desk config
	Env           map[string]string      `protobuf:"bytes,10,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`        // executor env from desk config
	Skills        []*Skill               `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`                                                                            // merged skill prompts/files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TaskRequest) GetEventPayload() []byte {
	if x != nil {
		return x.EventPayload
	}
	return nil
}

func (x *TaskRequest) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

func (x *TaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TaskRequest) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *TaskRequest) GetSession() []*Message {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *TaskRequest) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *TaskRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskRequest) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // resolved skill prompt text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// TaskEvent is streamed during execution.
// Intermediate events carry only a log entry.
// The final event carries the full result.
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`       // intermediate log (set on log events)
	Result        *TaskResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // final result (set on last event only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEvent) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *TaskEvent) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// TaskResult is the final outcome of agent execution.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emissions     []*EmitEvent           `protobuf:"bytes,1,rep,name=emissions,proto3" json:"emissions,omitempty"`
	NoteUpdates   []*NoteUpdate          `protobuf:"bytes,2,rep,name=note_updates,json=noteUpdates,proto3" json:"note_updates,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // non-empty = execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetEmissions() []*EmitEvent {
	if x != nil {
		return x.Emissions
	}
	return nil
}

func (x *TaskResult) GetNoteUpdates() []*NoteUpdate {
	if x != nil {
		return x.NoteUpdates
	}
	return nil
}

func (x *TaskResult) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "step" | "result"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Note) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Note) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeskId        string                 `protobuf:"bytes,1,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "assistant" | "tool"
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`            // "llm" | "script" | "resource"
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "exec" | "mcp" | "sdk"
	Actions       []*Action              `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exec          string                 `protobuf:"bytes,2,opt,name=exec,proto3" json:"exec,omitempty"` // exec 타입일 때 커맨드
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetExec() string {
	if x != nil {
		return x.Exec
	}
	return ""
}

type EmitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEvent) Reset() {
	*x = EmitEvent{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEvent) ProtoMessage() {}

func (x *EmitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEvent.ProtoReflect.Descriptor instead.
func (*EmitEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *EmitEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EmitEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NoteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"` // "set" | "delete"
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteUpdate) Reset() {
	*x = NoteUpdate{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteUpdate) ProtoMessage() {}

func (x *NoteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteUpdate.ProtoReflect.Descriptor instead.
func (*NoteUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *NoteUpdate) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *NoteUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NoteUpdate) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x0froster.agent.v1\"\xdc\x04\n" +
	"\vTaskRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\revent_payload\x18\x02 \x01(\fR\feventPayload\x12\x17\n" +
	"\adesk_id\x18\x03 \x01(\tR\x06deskId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x12+\n" +
	"\x05notes\x18\x06 \x03(\v2\x15.roster.agent.v1.NoteR\x05notes\x122\n" +
	"\asession\x18\a \x03(\v2\x18.roster.agent.v1.MessageR\asession\x127\n" +
	"\tresources\x18\b \x03(\v2\x19.roster.agent.v1.ResourceR\tresources\x12C\n" +
	"\aoptions\x18\t \x03(\v2).roster.agent.v1.TaskRequest.OptionsEntryR\aoptions\x127\n" +
	"\x03env\x18\n" +
	" \x03(\v2%.roster.agent.v1.TaskRequest.EnvEntryR\x03env\x12.\n" +
	"\x06skills\x18\v \x03(\v2\x16.roster.agent.v1.SkillR\x06skills\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"m\n" +
	"\tTaskEvent\x12+\n" +
	"\x03log\x18\x01 \x01(\v2\x19.roster.agent.v1.LogEntryR\x03log\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.roster.agent.v1.TaskResultR\x06result\"\x9c\x02\n" +
	"\n" +
	"TaskResult\x128\n" +
	"\temissions\x18\x01 \x03(\v2\x1a.roster.agent.v1.EmitEventR\temissions\x12>\n" +
	"\fnote_updates\x18\x02 \x03(\v2\x1b.roster.agent.v1.NoteUpdateR\vnoteUpdates\x12B\n" +
	"\ametrics\x18\x03 \x03(\v2(.roster.agent.v1.TaskResult.MetricsEntryR\ametrics\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"V\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\".\n" +
	"\x04Note\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x82\x01\n" +
	"\aMessage\x12\x17\n" +
	"\adesk_id\x18\x01 \x01(\tR\x06deskId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"a\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\aactions\x18\x03 \x03(\v2\x17.roster.agent.v1.ActionR\aactions\"0\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04exec\x18\x02 \x01(\tR\x04exec\"D\n" +
	"\tEmitEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"R\n" +
	"\n" +
	"NoteUpdate\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value2U\n" +
	"\fAgentService\x12E\n" +
	"\aExecute\x12\x1c.roster.agent.v1.TaskRequest\x1a\x1a.roster.agent.v1.TaskEvent0\x01B#Z!github.com/roster-io/roster/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: roster.agent.v1.TaskRequest
	(*Skill)(nil),       // 1: roster.agent.v1.Skill
	(*TaskEvent)(nil),   // 2: roster.agent.v1.TaskEvent
	(*TaskResult)(nil),  // 3: roster.agent.v1.TaskResult
	(*LogEntry)(nil),    // 4: roster.agent.v1.LogEntry
	(*Note)(nil),        // 5: roster.agent.v1.Note
	(*Message)(nil),     // 6: roster.agent.v1.Message
	(*Resource)(nil),    // 7: roster.agent.v1.Resource
	(*Action)(nil),      // 8: roster.agent.v1.Action
	(*EmitEvent)(nil),   // 9: roster.agent.v1.EmitEvent
	(*NoteUpdate)(nil),  // 10: roster.agent.v1.NoteUpdate
	nil,                 // 11: roster.agent.v1.TaskRequest.OptionsEntry
	nil,                 // 12: roster.agent.v1.TaskRequest.EnvEntry
	nil,                 // 13: roster.agent.v1.TaskResult.MetricsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	5,  // 0: roster.agent.v1.TaskRequest.notes:type_name -> roster.agent.v1.Note
	6,  // 1: roster.agent.v1.TaskRequest.session:type_name -> roster.agent.v1.Message
	7,  // 2: roster.agent.v1.TaskRequest.resources:type_name -> roster.agent.v1.Resource
	11, // 3: roster.agent.v1.TaskRequest.options:type_name -> roster.agent.v1.TaskRequest.OptionsEntry
	12, // 4: roster.agent.v1.TaskRequest.env:type_name -> roster.agent.v1.TaskRequest.EnvEntry
	1,  // 5: roster.agent.v1.TaskRequest.skills:type_name -> roster.agent.v1.Skill
	4,  // 6: roster.agent.v1.TaskEvent.log:type_name -> roster.agent.v1.LogEntry
	3,  // 7: roster.agent.v1.TaskEvent.result:type_name -> roster.agent.v1.TaskResult
	9,  // 8: roster.agent.v1.TaskResult.emissions:type_name -> roster.agent.v1.EmitEvent
	10, // 9: roster.agent.v1.TaskResult.note_updates:type_name -> roster.agent.v1.NoteUpdate
	13, // 10: roster.agent.v1.TaskResult.metrics:type_name -> roster.agent.v1.TaskResult.MetricsEntry
	8,  // 11: roster.agent.v1.Resource.actions:type_name -> roster.agent.v1.Action
	0,  // 12: roster.agent.v1.AgentService.Execute:input_type -> roster.agent.v1.TaskRequest
	2,  // 13: roster.agent.v1.AgentService.Execute:output_type -> roster.agent.v1.TaskEvent
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
