// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/resource.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceActionRequest) Reset() {
	*x = ResourceActionRequest{}
	mi := &file_proto_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceActionRequest) ProtoMessage() {}

func (x *ResourceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceActionRequest.ProtoReflect.Descriptor instead.
func (*ResourceActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceActionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResourceActionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ResourceActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceActionResponse) Reset() {
	*x = ResourceActionResponse{}
	mi := &file_proto_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceActionResponse) ProtoMessage() {}

func (x *ResourceActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceActionResponse.ProtoReflect.Descriptor instead.
func (*ResourceActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceActionResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ResourceActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_resource_proto protoreflect.FileDescriptor

const file_proto_resource_proto_rawDesc = "" +
	"\n" +
	"\x14proto/resource.proto\x12\x12roster.resource.v1\"\xda\x01\n" +
	"\x15ResourceActionRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12M\n" +
	"\x06params\x18\x03 \x03(\v25.roster.resource.v1.ResourceActionRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x16ResourceActionResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2y\n" +
	"\x0fResourceService\x12f\n" +
	"\rExecuteAction\x12).roster.resource.v1.ResourceActionRequest\x1a*.roster.resource.v1.ResourceActionResponseB#Z!github.com/roster-io/roster/protob\x06proto3"

var (
	file_proto_resource_proto_rawDescOnce sync.Once
	file_proto_resource_proto_rawDescData []byte
)

func file_proto_resource_proto_rawDescGZIP() []byte {
	file_proto_resource_proto_rawDescOnce.Do(func() {
		file_proto_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resource_proto_rawDesc), len(file_proto_resource_proto_rawDesc)))
	})
	return file_proto_resource_proto_rawDescData
}

var file_proto_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_resource_proto_goTypes = []any{
	(*ResourceActionRequest)(nil),  // 0: roster.resource.v1.ResourceActionRequest
	(*ResourceActionResponse)(nil), // 1: roster.resource.v1.ResourceActionResponse
	nil,                            // 2: roster.resource.v1.ResourceActionRequest.ParamsEntry
}
var file_proto_resource_proto_depIdxs = []int32{
	2, // 0: roster.resource.v1.ResourceActionRequest.params:type_name -> roster.resource.v1.ResourceActionRequest.ParamsEntry
	0, // 1: roster.resource.v1.ResourceService.ExecuteAction:input_type -> roster.resource.v1.ResourceActionRequest
	1, // 2: roster.resource.v1.ResourceService.ExecuteAction:output_type -> roster.resource.v1.ResourceActionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_resource_proto_init() }
func file_proto_resource_proto_init() {
	if File_proto_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resource_proto_rawDesc), len(file_proto_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resource_proto_goTypes,
		DependencyIndexes: file_proto_resource_proto_depIdxs,
		MessageInfos:      file_proto_resource_proto_msgTypes,
	}.Build()
	File_proto_resource_proto = out.File
	file_proto_resource_proto_goTypes = nil
	file_proto_resource_proto_depIdxs = nil
}
