// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DeskId       string                 `protobuf:"bytes,2,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`
	ExecutorType string                 `protobuf:"bytes,3,opt,name=executor_type,json=executorType,proto3" json:"executor_type,omitempty"`                                             // api | exec | docker
	Prompt       string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                             // merged skill prompts + input context
	Options      map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // executor-specific params (model, command, image…)
	Env          map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`         // environment variables
	InputPayload []byte                 `protobuf:"bytes,7,opt,name=input_payload,json=inputPayload,proto3" json:"input_payload,omitempty"`                                             // serialised input Artifact payload (optional)
	// Session context
	Session       []*SessionEntry `protobuf:"bytes,8,rep,name=session,proto3" json:"session,omitempty"`                               // desk's persistent conversation history
	GroupHistory  []*GroupMessage `protobuf:"bytes,9,rep,name=group_history,json=groupHistory,proto3" json:"group_history,omitempty"` // active group's shared messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecuteRequest) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

func (x *ExecuteRequest) GetExecutorType() string {
	if x != nil {
		return x.ExecutorType
	}
	return ""
}

func (x *ExecuteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetInputPayload() []byte {
	if x != nil {
		return x.InputPayload
	}
	return nil
}

func (x *ExecuteRequest) GetSession() []*SessionEntry {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ExecuteRequest) GetGroupHistory() []*GroupMessage {
	if x != nil {
		return x.GroupHistory
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // non-empty = execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ExecuteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SessionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant" | "system"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEntry) Reset() {
	*x = SessionEntry{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEntry) ProtoMessage() {}

func (x *SessionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEntry.ProtoReflect.Descriptor instead.
func (*SessionEntry) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *SessionEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GroupMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeskId        string                 `protobuf:"bytes,1,opt,name=desk_id,json=deskId,proto3" json:"desk_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *GroupMessage) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

func (x *GroupMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\x10roster.worker.v1\"\x9f\x04\n" +
	"\x0eExecuteRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\adesk_id\x18\x02 \x01(\tR\x06deskId\x12#\n" +
	"\rexecutor_type\x18\x03 \x01(\tR\fexecutorType\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12G\n" +
	"\aoptions\x18\x05 \x03(\v2-.roster.worker.v1.ExecuteRequest.OptionsEntryR\aoptions\x12;\n" +
	"\x03env\x18\x06 \x03(\v2).roster.worker.v1.ExecuteRequest.EnvEntryR\x03env\x12#\n" +
	"\rinput_payload\x18\a \x01(\fR\finputPayload\x128\n" +
	"\asession\x18\b \x03(\v2\x1e.roster.worker.v1.SessionEntryR\asession\x12C\n" +
	"\rgroup_history\x18\t \x03(\v2\x1e.roster.worker.v1.GroupMessageR\fgroupHistory\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\fSessionEntry\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\fGroupMessage\x12\x17\n" +
	"\adesk_id\x18\x01 \x01(\tR\x06deskId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent2X\n" +
	"\x06Worker\x12N\n" +
	"\aExecute\x12 .roster.worker.v1.ExecuteRequest\x1a!.roster.worker.v1.ExecuteResponseB#Z!github.com/roster-io/roster/protob\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_worker_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: roster.worker.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: roster.worker.v1.ExecuteResponse
	(*SessionEntry)(nil),    // 2: roster.worker.v1.SessionEntry
	(*GroupMessage)(nil),    // 3: roster.worker.v1.GroupMessage
	nil,                     // 4: roster.worker.v1.ExecuteRequest.OptionsEntry
	nil,                     // 5: roster.worker.v1.ExecuteRequest.EnvEntry
}
var file_proto_worker_proto_depIdxs = []int32{
	4, // 0: roster.worker.v1.ExecuteRequest.options:type_name -> roster.worker.v1.ExecuteRequest.OptionsEntry
	5, // 1: roster.worker.v1.ExecuteRequest.env:type_name -> roster.worker.v1.ExecuteRequest.EnvEntry
	2, // 2: roster.worker.v1.ExecuteRequest.session:type_name -> roster.worker.v1.SessionEntry
	3, // 3: roster.worker.v1.ExecuteRequest.group_history:type_name -> roster.worker.v1.GroupMessage
	0, // 4: roster.worker.v1.Worker.Execute:input_type -> roster.worker.v1.ExecuteRequest
	1, // 5: roster.worker.v1.Worker.Execute:output_type -> roster.worker.v1.ExecuteResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
